### ISSUE TITLE
Add support for xcscheme TestableReferences to enable subproject unit testing

### ISSUE THREAD

**Issue by raptorxcz** [lyptt/struct#167]
##New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

3.2.0

## Spec version

2.2.0

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

I have 2 project files. One for application and one for framework. When I run applications unit tests I want run frameworks unit tests as well. I can manually add frameworks unit tests to applications unit tests. Is this possible with struct?

**Comment by lyptt** [comment]
Hey @raptorxcz, I think this would work by making use of the subproject feature to link your application to your framework. Xcode should then pick up the fact that the framework has unit tests, so when you hit Cmd+U you'll get both being run.

As an example:

```yaml
- location: Carthage/Checkouts/BrightFutures/BrightFutures.xcodeproj
      frameworks:
      - name: BrightFutures.framework
        copy: true
        codeSignOnCopy: false
```

**Comment by lyptt** [comment]
FWIW if the above doesn't work but it does work without struct, then definitely feel free to attach an example of the above but created without struct. That way I can examine the project files and figure out what extra I need to do.

**Comment by raptorxcz** [comment]
Thanks for feedback. I am not sure if I get it right. I have this in project.yml:

```
---
version: 2.2.0
...
targets:
    App:
      ...
      references:
        - location: ../../Modules/Framework/Framework.xcodeproj
          frameworks:
            - name: Framework.framework
              copy: true
              codeSignOnCopy: true
    ...

schemes:
    App:
      ...
      build:
        parallel: false
        build_configuration: Debug
        build_implicit: true
        targets:
          App:
            archiving_enabled: true
            running_enabled: true
            profiling_enabled: true
            testing_enabled: true
            analyzing_enabled: true
          FrameworkTests:
            archiving_enabled: false
            running_enabled: false
            profiling_enabled: false
            testing_enabled: true
            analyzing_enabled: false
      test:
        build_configuration: debug
        inherit_launch_arguments: true
        targets:
          - App
          - FrameworkTests
  ...

variants:
  $base:
    abstract: true
  App:
```
