### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET issue

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#37]
Here is my config: https://www.dropbox.com/s/o10vsr2r5kcke5o/project.yml?dl=0

I included `IPHONEOS_DEPLOYMENT_TARGET` setting into `CommonSettings`:

```YAML
IPHONEOS_DEPLOYMENT_TARGET: '8.0'
```

then I include them into each configuration on project level:

```YAML
configurations:

    *cfgDebug:
        type: debug
        profiles:
        - general:debug
        - ios:debug
        overrides:
            *CommonSettings

    #---
    
    *cfgRelease:
        type: release
        profiles:
        - general:release
        - ios:release
        overrides:
            *CommonSettings
```

but when I'm trying to generate the project, I'm getting strange error as follows:

`[Xcodeproj] Consistency issue: build setting `IPHONEOS_DEPLOYMENT_TARGET` has multiple values: `{"Debug"=>"10.2", "Release"=>"8.0"}`

Any ideas why?
