### ISSUE TITLE
Embed Library

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#40]
In Xcake some of our users need a way to embed or link to a library generated by a target in their project in another target.

It would be great if Struct could do this too (I use this for a couple of things).

**Comment by lyptt** [comment]
Hi @jcampbell05, yes embedding local libraries is definitely something struct should support. This would be primarily used for extending Objective-C support, as Swift targets are always embedded frameworks due to the necessity to bundle the Swift runtime.

**Comment by lyptt** [comment]
Proposed schema adjustment as follows:

```yaml
targets:
  My target:
    references:
    - location: libs/libGoogleAnalytics.a
```

```ruby
spec('1.2.0') do
  target('My target') do
    library_reference 'libs/libGoogleAnalytics.a'
```
