### ISSUE TITLE
Add support for multiple options with run script ordering

### ISSUE THREAD

**Issue by lyptt** [lyptt/struct#5]
Currently run scripts are only added to the end of the build phases list. This enhancement will allow for run scripts to be added to the start or end of the list via an extension to the current schema.

Proposed schema adjustment would be as follows:

```yaml
targets:
  My app:
    scripts:
      prebuild:
      - scripts/lint.sh
      postbuild:
      - scripts/strip-architectures.sh
```

Parsing flow as follows:

- If `scripts` value is a hash, look for `prebuild` and `postbuild` keys
  - Validate `prebuild` and `postbuild` as hashes, if they are not hashes, raise a warning and skip these keys
  - Validate each file reference in `prebuild` and `postbuild`, for any scripts that do not exist, ignore them and raise a warning
- If `scripts` value is a string, process as normal and add to `postbuild` to retain backwards compatibility with spec 1.1.0

Generation flow as follows:

- Iterate through `prebuild` scripts, processing with existing logic. Add each processed run script phase to index 0 of build phases
- Iterate through `postbuild` scripts, processing with existing logic. Add each processed run script phase to the end of the build phases list
