### ISSUE TITLE
Xcode crashes when trying to open project file

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#77]
I use Ruby 2.4.0 via RVM. With latest Struct. I prepared YAML spec file and generated project file. Operation went normally, no even warnings nor errors. But when I'm trying to open the project file (double click or add to workspace) - Xcode crashes. Any ideas how to fix? Thanks!

The spec file: https://www.dropbox.com/s/or9bram5jujxgxs/project.yml?dl=0
The generated project file: https://www.dropbox.com/sh/r9xfkazxwudzi8t/AABkjXLyaLUQS6PepoQtnOy6a?dl=0
The Xcode crash details: https://www.dropbox.com/s/7yzy53psvyvlho2/XcodeCrash.txt?dl=0

**Comment by lyptt** [comment]
This is probably a missing configuration setting. Xcode isn't particularly friendly in this regard.

Could you provide the full set of project files? Otherwise this may make reproduction harder as Xcode refuses to load projects fully unless the Info.plist for example is present.

**Comment by maximkhatskevich** [comment]
@lyptt yes, sure, it's on top of the 'develop' branch (just pushed): https://github.com/maximkhatskevich/MKHRequirement/tree/develop

**Comment by maximkhatskevich** [comment]
@lyptt just wondering - can you reproduce the crash?

**Comment by lyptt** [comment]
@maximkhatskevich I've reproduced it, you're not defining the configuration correctly for your targets.

A quote from the [wiki](https://github.com/lyptt/struct/wiki/Spec-format%3A-v1.2#target-configuration):

> A target can be configured in one of three ways - by specifying its platform, by specifying a series of configuration profiles, or by specifying an xcconfig reference.

You're mixing up 'project configuration' with 'target configuration'. Targets are not configured identically to projects, and as a result you're inserting data into your build settings that Xcode is not equipped to handle.

A target configuration block is a hash of _overrides_, not a configuration hash like the one defined on a project-level.

You should declare your target type, then either the platform, or an array of configuration profiles to apply to that target. You may then _optionally_ specify configuration overrides with configuration or configurations depending on your needs.

**Comment by maximkhatskevich** [comment]
@lyptt okay, I see your point, but what exactly should I change in the 'project.yml' file to make the generated project file work normally?

**Comment by maximkhatskevich** [comment]
If I just remove the 'profiles' entries from both configurations - it does not help.

**Comment by lyptt** [comment]
Strip out the configurations blocks from your targets, remove anything to do with 'profiles', etc from these blocks. 

Take the overrides keys and values - these are what go directly inside 'Debug' and 'Release' on a target level.

**Comment by lyptt** [comment]
Please look at the example projects for reference, you'll notice there's nothing in 'configuration' other than overrides.

**Comment by maximkhatskevich** [comment]
Okay, thanks!

**Comment by maximkhatskevich** [comment]
@lyptt in the example spec file you apply both [platform](https://github.com/lyptt/struct/blob/master/examples/iOS_Framework/project.yml#L19) and [profiles](https://github.com/lyptt/struct/blob/master/examples/iOS_Framework/project.yml#L21). But it does not cause a crash.

**Comment by lyptt** [comment]
Hi @maximkhatskevich, I think you're misunderstanding what's wrong with your spec file. Let me demonstrate with sample code.

Here is what you're currently doing:

```yaml
Tests:
    platform: ios
    type: ":bundle.unit-test"
    configurations:
      Debug:
        type: debug
        profiles:
        - platform:ios
        - bundle.unit-test
        - ios:debug
        overrides:
          PRODUCT_BUNDLE_IDENTIFIER: khatskevich.maxim.MKHRequirement.Tst
          INFOPLIST_FILE: Info/Tst.plist
          FRAMEWORK_SEARCH_PATHS: $(inherited) $(BUILT_PRODUCTS_DIR)
```

Here is what you should change this to:

```yaml
Tests:
    platform: ios
    type: ":bundle.unit-test"
    configurations:
      Debug:
        PRODUCT_BUNDLE_IDENTIFIER: khatskevich.maxim.MKHRequirement.Tst
        INFOPLIST_FILE: Info/Tst.plist
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(BUILT_PRODUCTS_DIR)
```

Does that help?
